---
- name: HANA check - Wait pacemaker up
  become: true
  command: systemctl --no-pager is-active pacemaker
  register: pm
  retries: "{{ pacemaker_timeout // 15 }}"
  delay: 15
  until: pm.stdout == 'active'

- name: HANA check - Wait cluster idle again
  become: true
  command: cs_wait_for_idle --sleep 5
  register: idle2
  retries: "{{ cs_wait_timeout // 5 }}"
  delay: 5
  until: idle2.rc == 0

- name: HANA check – wait until topology shows 1 PRIM and the rest SOK
  become: true
  command: SAPHanaSR-showAttr --format=script
  register: topo_raw
  changed_when: false
  delay: 10
  retries: 6
  until: >
    (
      (topo_raw.stdout_lines
         | select('search', 'sync_state="PRIM"')
         | list | length) == 1
    )
    and
    (
      (topo_raw.stdout_lines
         | select('search', 'sync_state="SOK"')
         | list | length) ==
      (
        (topo_raw.stdout_lines
           | select('search', '^Hosts/')
           | map('regex_replace', '^Hosts/([^/]+)/.*', '\\1')
           | list | unique | length) - 1
      )
    )

- name: Post HANA check - crm cleanup
  become: true
  command: crm resource cleanup
