---
- name: SAP HANA takeover – disruptive node
  hosts: "{{ node_name }}"
  gather_facts: no
  vars:
    peer_site: "{{ (groups['hana'] | difference([node_name]))[0] }}"
  roles:
    - hana_actions

- name: SAP HANA takeover – cluster validation
  hosts: hana
  gather_facts: no
  serial: 1
  vars:
    peer_site: "{{ (groups['hana'] | difference([node_name]))[0] }}"
  roles:
    - hana_checks
