---
- name: SAP HANA secondary-site failure test
  hosts: "{{ node_name }}"
  gather_facts: no
  vars:
    peer_site: "{{ (groups['hana'] | difference([node_name]))[0] }}"
  roles:
    - hana_secondary_actions
